version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
    - .:/app
    ports:
    - 8080:8000
    env_file:
    - .env
    # watchout! very dangerous!
    # ref: https://phoenixnap.com/kb/docker-privileged
    privileged: true
    command: sh -c "openfortivpn -c $VPN_NAME.conf & tail -f /dev/null"

